name = "ethicaltransparency-news-frontend"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "ethicaltransparency-news-db"
database_id = "e7cfc685-fd56-4195-8012-670f82175b75"

